### ISSUE TITLE
Delete marker by Id

### ISSUE THREAD

**Issue by Nandite** [davetcoleman/rviz_visual_tools#33]
@VictorLamoine ,Currently when we call the function deleteAllMarkers(), it remove every markers added in RViz. It would be great to have a function deleteMarkerById(), since we do not want to remove marker drawn on the screen at one time.

Sincerely

**Comment by davetcoleman** [comment]
Yes that would be a good feature to add - Rviz would support it!

**Comment by VictorLamoine** [comment]
It would also be nice to have a DeleteAllBut and specifying a list of ID's to keep

**Comment by davetcoleman** [comment]
This would be more complicated because we'd have to track all object IDs that have been published and maintain that list throughout - I'm not sure the overhead is worth it. In my workflow, I always just delete everything and redraw the scene

**Comment by davetcoleman** [comment]
I do not plan on implementing this, are you guys working on an implementation?

**Comment by VictorLamoine** [comment]
No not for now, maybe in the future
