### ISSUE TITLE
Travis failure related to Eigen3

### ISSUE THREAD

**Issue by VictorLamoine** [davetcoleman/rviz_visual_tools#38]
https://travis-ci.org/davetcoleman/rviz_visual_tools/builds/141027369#L1674

~~I'm not sure where this `FindEigen3.cmake` comes from, ROS Kinetic provides it?~~
CMake provides it starting from CMake 3

**Comment by davetcoleman** [comment]
Fix via switching to ROS buildfarm CI: https://travis-ci.org/davetcoleman/rviz_visual_tools/builds/141171171
