### ISSUE TITLE
topic can't connect to any subscriber

### ISSUE THREAD

**Issue by ruinianxu** [davetcoleman/rviz_visual_tools#54]
I was running move_group_interface_tutorial.launch but I got the warn that Topic '/rviz_visual_tools' unable to connect to any subscribers within 0.5 sec. It is possible initially published visual messages will be lost. It is wired since I was able to run this tutorial several days ago and I didn't change any code but just did something about debugging code by using eclipse. Is this because of eclipse?

**Comment by davetcoleman** [comment]
i can't help you with your personal text editor.

the message is often a timing issue... if you have a slow computer the two processes might not connect in time.
