### ISSUE TITLE
Warnings in test compilation

### ISSUE THREAD

**Issue by VictorLamoine** [davetcoleman/rviz_visual_tools#58]
Lots of them:
```bash
/home/victor/code/catkin_workspace/src/rviz_visual_tools/tests/rvt_test.cpp: In member function ‘virtual void RVTTest_test_rpy_conversions_Test::TestBody()’:
/home/victor/code/catkin_workspace/src/rviz_visual_tools/tests/rvt_test.cpp:128:82: warning: ‘static Eigen::Affine3d rviz_visual_tools::RvizVisualTools::convertFromXYZRPY(std::vector<double>)’ is deprecated [-Wdeprecated-declarations]
   Eigen::Affine3d expected_affine2 = base.visual_tools_->convertFromXYZRPY(xyzrpy);
                                                                                  ^
```

**Comment by davetcoleman** [comment]
Yes I recently made a change that deprecated the ambiguous version of convertFromXYZRPY() and it now requires you say what kind of Euler angles you are using:

> convertFromXYZRPY(x, y, z, roll, pitch, yaw, rviz_visual_tools::XYZ);

See https://github.com/davetcoleman/rviz_visual_tools/blob/kinetic-devel/include/rviz_visual_tools/rviz_visual_tools.h#L949

If you could make that change that would be awesome - my current projects are not using rviz_visual_tools.

**Comment by VictorLamoine** [comment]
After the holidays then :)
