### ISSUE TITLE
ambiguous function call

### ISSUE THREAD

**Issue by mcevoyandy** [davetcoleman/rviz_visual_tools#62]
Noticed this tonight. The Eigen version does not have a default value for `length`. I assume the `geometry_msgs` version should match?

https://github.com/davetcoleman/rviz_visual_tools/blob/02579b4742fc6cba463a420de6ecf37bbfea1193/include/rviz_visual_tools/rviz_visual_tools.h#L759
https://github.com/davetcoleman/rviz_visual_tools/blob/02579b4742fc6cba463a420de6ecf37bbfea1193/include/rviz_visual_tools/rviz_visual_tools.h#L761

**Comment by davetcoleman** [comment]
your fix is https://github.com/davetcoleman/rviz_visual_tools/pull/63 correct?
